name: build-and-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
      - name: Package application
        run: |
          jpackage --input target \
                   --name ChatDelta \
                   --main-jar chatdelta-java-0.1.0.jar \
                   --main-class com.chatdelta.Main \
                   --type app-image \
                   --dest dist
        shell: bash
      - name: Archive package
        run: |
          tar -czf ChatDelta-${{ matrix.os }}.tar.gz -C dist ChatDelta
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChatDelta-${{ matrix.os }}
          path: ChatDelta-${{ matrix.os }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
